const ADJECTIVES = [
  'able', 'adept', 'agile', 'alert', 'alive', 'ample', 'apt', 'avid',
  'aware', 'azure', 'bare', 'basic', 'bliss', 'blunt', 'bold', 'brash',
  'brave', 'brief', 'brisk', 'broad', 'busy', 'calm', 'civic', 'clean',
  'clear', 'close', 'cool', 'core', 'cozy', 'crisp', 'curly', 'daily',
  'dark', 'dear', 'deep', 'deft', 'dense', 'dizzy', 'dry', 'dual',
  'eager', 'early', 'easy', 'edgy', 'elfin', 'elite', 'epic', 'equal',
  'exact', 'extra', 'faint', 'fair', 'fancy', 'fast', 'feral', 'fierce',
  'fiery', 'fine', 'firm', 'first', 'fit', 'fleet', 'fluid', 'flush',
  'focal', 'fond', 'frank', 'free', 'fresh', 'full', 'fun', 'fuzzy',
  'game', 'glad', 'gold', 'good', 'grand', 'great', 'green', 'grim',
  'gross', 'grown', 'gusty', 'happy', 'hardy', 'hasty', 'hazel', 'hefty',
  'high', 'home', 'hot', 'huge', 'human', 'icy', 'ideal', 'inner',
  'ionic', 'iron', 'ivory', 'jade', 'jazzy', 'jolly', 'just', 'keen',
  'kind', 'known', 'lanky', 'large', 'laser', 'late', 'leafy', 'lean',
  'level', 'light', 'lithe', 'live', 'local', 'lone', 'long', 'loud',
  'loyal', 'lucid', 'lucky', 'lunar', 'lusty', 'magic', 'main', 'major',
  'maple', 'meek', 'merry', 'mild', 'mint', 'misty', 'mixed', 'modal',
  'moist', 'moody', 'moral', 'muddy', 'muted', 'naive', 'naval', 'neat',
  'new', 'next', 'nice', 'nimble', 'noble', 'noted', 'novel', 'oaken',
  'odd', 'olive', 'only', 'open', 'opted', 'oral', 'other', 'outer',
  'oval', 'own', 'pale', 'pasty', 'peak', 'perky', 'petty', 'pilot',
  'pine', 'pink', 'plain', 'plumb', 'plump', 'plush', 'polar', 'polka',
  'prime', 'prior', 'proud', 'pure', 'pushy', 'quick', 'quiet', 'rabid',
  'rapid', 'rare', 'raspy', 'raw', 'ready', 'real', 'red', 'regal',
  'rich', 'rigid', 'ripe', 'risen', 'risky', 'ritzy', 'rival', 'roast',
  'rocky', 'roman', 'roomy', 'rosy', 'rough', 'round', 'royal', 'ruby',
  'runic', 'rural', 'rusty', 'safe', 'sage', 'salty', 'same', 'sandy',
  'sane', 'savvy', 'scaly', 'sharp', 'sheer', 'shiny', 'short', 'shy',
  'silky', 'slim', 'slow', 'small', 'smart', 'smoky', 'snowy', 'snug',
  'sober', 'soft', 'solar', 'solid', 'sonic', 'sorry', 'sound', 'south',
  'spare', 'spicy', 'spry', 'squat', 'stale', 'stark', 'steel', 'steep',
  'stern', 'stiff', 'still', 'stoic', 'stone', 'stout', 'suave', 'sunny',
  'super', 'sure', 'sweet', 'swift', 'tall', 'tame', 'tan', 'tangy',
  'tart', 'taut', 'teal', 'tepid', 'thick', 'thin', 'tidy', 'tight',
  'tiny', 'token', 'top', 'total', 'tough', 'trim', 'true', 'tubby',
  'twin', 'ultra', 'uncut', 'under', 'undue', 'unfit', 'upper', 'urban',
  'used', 'usual', 'utter', 'vague', 'valid', 'vast', 'velvet', 'vivid',
  'vocal', 'wacky', 'warm', 'wary', 'wavy', 'waxy', 'weak', 'weary',
  'weird', 'west', 'wet', 'white', 'whole', 'wide', 'wild', 'wily',
  'windy', 'wired', 'wise', 'witty', 'woke', 'woody', 'wry', 'young',
  'zany', 'zappy', 'zeal', 'zen', 'zesty', 'zippy',
]

const NOUNS = [
  'ace', 'acorn', 'agent', 'alder', 'alloy', 'amber', 'anvil', 'apex',
  'arch', 'arrow', 'aspen', 'atlas', 'atom', 'axle', 'badge', 'basin',
  'bass', 'beam', 'bench', 'birch', 'blade', 'blaze', 'bloom', 'bluff',
  'board', 'bolt', 'bond', 'bower', 'brace', 'brand', 'brass', 'brick',
  'brook', 'brush', 'bugle', 'cairn', 'canal', 'cape', 'cargo', 'cedar',
  'chain', 'charm', 'chess', 'chime', 'chord', 'clamp', 'clay', 'cliff',
  'clock', 'cloud', 'clove', 'coach', 'coast', 'comet', 'coral', 'core',
  'crane', 'crate', 'creek', 'crest', 'cross', 'crown', 'crush', 'crypt',
  'cube', 'curve', 'cycle', 'darts', 'dawn', 'delta', 'depot', 'dew',
  'digit', 'dingo', 'disk', 'ditch', 'dock', 'dome', 'dove', 'draft',
  'drake', 'drift', 'drone', 'drum', 'dune', 'dwarf', 'eagle', 'earth',
  'easel', 'edge', 'elm', 'ember', 'facet', 'fawn', 'ferry', 'fiber',
  'finch', 'fjord', 'flame', 'flask', 'flax', 'fleet', 'flint', 'flock',
  'flora', 'flute', 'focus', 'forge', 'fort', 'frame', 'frost', 'fruit',
  'gale', 'gauge', 'gavel', 'gecko', 'geyser', 'ghost', 'glade', 'gleam',
  'glint', 'globe', 'glyph', 'gnome', 'goose', 'gorge', 'grain', 'grape',
  'graph', 'grasp', 'grove', 'guild', 'gull', 'gusto', 'haven', 'hawk',
  'hazel', 'heath', 'hedge', 'heron', 'hinge', 'holly', 'hound', 'hull',
  'hyena', 'index', 'ingot', 'inlet', 'ivory', 'jay', 'jewel', 'joint',
  'kelp', 'ketch', 'knack', 'knoll', 'knot', 'kraft', 'lance', 'larch',
  'lark', 'latch', 'lathe', 'ledge', 'lever', 'light', 'lilac', 'linen',
  'links', 'llama', 'lodge', 'loft', 'lotus', 'lunar', 'lynch', 'lynx',
  'mango', 'manor', 'maple', 'marsh', 'mast', 'maxim', 'mesa', 'meter',
  'mills', 'miner', 'mint', 'mirth', 'moat', 'model', 'molar', 'moose',
  'morph', 'morse', 'motor', 'mound', 'mulch', 'mural', 'myrrh', 'nerve',
  'nexus', 'niche', 'node', 'notch', 'novel', 'oak', 'oasis', 'ocean',
  'olive', 'onset', 'onyx', 'opera', 'orbit', 'orca', 'osprey', 'otter',
  'oxide', 'ozone', 'panda', 'panel', 'patch', 'path', 'pearl', 'pecan',
  'perch', 'phase', 'pilot', 'pine', 'pixel', 'plank', 'plant', 'plaza',
  'plume', 'point', 'polar', 'pond', 'poppy', 'port', 'pouch', 'press',
  'prism', 'probe', 'prose', 'prowl', 'pulse', 'pylon', 'quail', 'quest',
  'quill', 'quota', 'rafter', 'rail', 'range', 'raven', 'realm', 'reed',
  'reef', 'reign', 'relay', 'ridge', 'rivet', 'robin', 'roost', 'rover',
  'ruby', 'sage', 'sail', 'salon', 'scale', 'scone', 'scope', 'scout',
  'seal', 'sedge', 'shade', 'shaft', 'shell', 'shelf', 'shoal', 'shore',
  'shrew', 'shrub', 'sigma', 'siren', 'skimp', 'slate', 'sleet', 'slope',
  'smith', 'snare', 'solar', 'sonic', 'spark', 'spear', 'spire', 'spoke',
  'spore', 'spray', 'squid', 'staff', 'stage', 'stake', 'stalk', 'steam',
  'steel', 'stern', 'stone', 'storm', 'stove', 'stump', 'surge', 'swamp',
  'swift', 'thorn', 'tiger', 'tile', 'timer', 'token', 'torch', 'totem',
  'tower', 'trace', 'trail', 'trend', 'tribe', 'trout', 'trunk', 'tulip',
  'tundra', 'tuner', 'tweed', 'twig', 'umbra', 'union', 'valve', 'vapor',
  'vault', 'venom', 'verge', 'verse', 'vigor', 'vine', 'viola', 'viper',
  'visor', 'vivid', 'vortex', 'wafer', 'warden', 'watch', 'wedge', 'whale',
  'wheat', 'wheel', 'whirl', 'wicker', 'willow', 'wing', 'wren', 'yacht',
  'yew', 'yield', 'zebra', 'zinc', 'zone',
]

function randomElement<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)]
}

export function generateId(existingIds: Set<string>, maxRetries = 100): string {
  for (let i = 0; i < maxRetries; i++) {
    const id = `${randomElement(ADJECTIVES)}-${randomElement(NOUNS)}`
    if (!existingIds.has(id)) return id
  }
  throw new Error('Could not generate a unique ID after 100 attempts')
}

export { ADJECTIVES, NOUNS }
